region                  = "ap-southeast-1"
network_border_group    = "ap-southeast-1-bkk-1"
cluster_name            = "kubeip-lz-cluster"
kubeip_role_arn         = "arn:aws:iam::905418473443:role/kubeip-agent-role"
kubeip_sa_name          = "kubeip-agent-sa"